server:
  port: 8002
spring:
  application:
    name: server
#热部署配置
  devtools:
    restart:
      additional-paths: src/main/java

eureka:
  client:
    service-url:
      defaultZone: http://${center.user.username}:${center.user.password}@localhost:8001/eureka/

center:
  user:
    username: yubaoqi
    password: yubaoqi