spring:
  application:
    name: client
  #热部署配置
  devtools:
    restart:
      additional-paths: src/main/java

server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/