spring:
  application:
    name: client
  #热部署配置
  devtools:
    restart:
      additional-paths: src/main/java

server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://${center.user.name}:${center.user.password}@localhost:8001/eureka/
management:
 server:
   port: 9000
 endpoints:
   web:
     base-path: /
     exposure:
       include: "*"

center:
  user:
    name: yubaoqi
    password: yubaoqi