spring:
  application:
    name: config-client
  cloud:
    config:
      name: ${spring.application.name}
server:
  port: 8009

eureka:
  client:
    service-url:
      defaultZone: http://${center.user.name}:${center.user.password}@localhost:8001/eureka/

center:
  user:
    name: yubaoqi
    password: yubaoqi

#打开actuator监控端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
