spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: F:/idea/testconfig/  #配置本地配置文件

server:
  port: 8008

eureka:
  client:
    service-url:
      defaultZone: http://${center.user.name}:${center.user.password}@localhost:8001/eureka/

center:
  user:
    name: yubaoqi
    password: yubaoqi